// Backend API base URL — the ONE place to change when deploying.
//
// Local dev: leave as-is (matches `uvicorn app.main:app` default port).
// Render: this file is regenerated by the frontend static site's build
// command from the API_BASE environment variable — see render.yaml.
window.CARECREW_API_BASE = "http://localhost:8000";
